services:
  app:
    container_name: arxivchatguru-app
    build:
      context: .
    ports:
      - "8501:8501"
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - redis
  redis:
    image: redis:alpine
    container_name: arxivchatguru-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data:
